### ISSUE TITLE
exometer tty is not reporting

### ISSUE THREAD

**Issue by blt** [blt/robot_utopia#2]
## Description

In the branch anchored at 288d2c62f151cecfa6a6ac49eeb1f73e929c20c1 I have exometer_core built in a rebar3 project, configured to collect a handful of metrics and report these out through the TTY reporter. This is all curiously silent though and exometer doesn't seem to be calling the functions to fill up the metrics. 

I'm not certain if this is a problem when building exometer_core under rebar3 or a matter of configuration. @uwiger do you see anything with the configuration--in `config/sys.config`--that is obviously dotty? 
## To Reproduce

```
$ make console
```

Wait for a bit, see no output. 

```
> dbg:stop_clear(), dbg:tracer(process, {fun (_,10) -> dbg:stop_clear(); (Msg, N) -> io:format("~p~n", [Msg]), N+1 end, 0}), dbg:p(all, c), dbg:tpl(robot_utopia, x).
{ok,[{matched,'robot_utopia@walden-2.marineclub.com',3},
      {saved,x}]}
```

Note the lack of calls to `robot_utopia:humans_macerated()`

**Comment by uwiger** [comment]
Sorry for the delay.

I see two issues with your `sys.config`:
- You specify environment for `exometer`, but your dependency is only to `exometer_core`. This means the application controller will never load the exometer config.
- You don't seem to have a `reporters` section, and thus no start config for exometer_report_tty.

**Comment by uwiger** [comment]
I was able to at least break the silence with this config:

``` erlang
[
 {'robot_utopia', []},

 {exometer_core,
  [
   {predefined,
    [
     ...
    ]
   },

   {reporters,
    [
     {exometer_report_tty, [{module,exometer_report_tty}]}
    ]},
   {subscribers,
    [
     ...
    ]}
  ]}
].
```

**Comment by blt** [comment]
Ah, that's my problem. I didn't realize that exometer_core would not read exometer configuration. Thank you! 

—

**Comment by uwiger** [comment]
Well, it will, if the exometer application is loaded. The problem is that the application controller won't load the config, since the exometer app isn't present.

**Comment by uwiger** [comment]
I realize that this needs to be made clear in the documentation. :)

**Comment by blt** [comment]
I appreciate the help! :)
